spring:
  datasource:
    url: jdbc:postgresql://localhost/ninja_database
    username: ninja
    password: ninja
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 707167609466-40pekve7j2peuaf08b9e7jf8jdbp3hd7.apps.googleusercontent.com
            clientSecret: ILwB054_dK4tFTNknvuj0M0v
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: classpath:session_tables.sql
server:
  port: 9000
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8000
