version: '3.9'
services:
  database:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ninja
      POSTGRES_PASSWORD: ninja
      POSTGRES_DB: ninja_database
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5024:5432"
volumes:
  postgres: