name: Vue Linter Schedule

on:
  schedule:
    - cron: "0 11 * * *"

jobs:
  build:
    name: checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Vue linter with Maven
      run: mvn -B clean validate -DskipTests
