name: Vue Linter

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -B clean validate -DskipTests
